# OrchestrateX Docker Compose Configuration
# MongoDB service for multi-AI orchestration system

services:
  project-mongodb:
    image: mongo:8.0
    container_name: orchestratex_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-rootPassword123}
    volumes:
      - orchestratex_data:/data/db
      - ./database/init_db.js:/docker-entrypoint-initdb.d/01-init_db.js:ro
    networks:
      - orchestratex_network

  mongo-express:
    image: mongo-express:latest
    container_name: orchestratex_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: project-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://project-mongodb:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS:-admin}
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    depends_on:
      - project-mongodb
    networks:
      - orchestratex_network
volumes:
  orchestratex_data:
    driver: local

networks:
  orchestratex_network:
    driver: bridge