version: '3.8'

services:
  # Full-stack OrchestrateX (Frontend + Backend)
  orchestratex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - DEBUG=false
    env_file:
      - orche.env
    depends_on:
      - mongodb
    restart: unless-stopped

  # MongoDB Database (Optional - can use external DB)
  mongodb:
    image: mongo:8.0
    container_name: orchestratex_mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-rootPassword123}
    volumes:
      - orchestratex_data:/data/db
    networks:
      - orchestratex_network

volumes:
  orchestratex_data:
    driver: local

networks:
  orchestratex_network:
    driver: bridge