@echo off
echo Starting OrchestrateX Landing Page...
cd /d "c:\Users\91903\OneDrive\Documents\OrchestrateX\FRONTEND\LANDING PAGE\landingpage\project"
echo Installing dependencies...
npm install
echo Starting development server on port 3000...
npm run dev
pause
