version: '3.9'
services:
  mongo:
    image: mongo:7.0
    container_name: orchestratex-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: orchestratex
      MONGO_INITDB_ROOT_PASSWORD: changeMeDev!
    volumes:
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - orchestratex-net

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: orchestratex-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: orchestratex
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeMeDev!
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - orchestratex-net

volumes:
  mongo-data:

networks:
  orchestratex-net:
    driver: bridge
